# Generated by Django 5.2.6 on 2025-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidante',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='leader',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leader',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
