# Generated by Django 5.2.6 on 2025-10-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_candidante_password_alter_leader_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='city_company',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='name_company',
            new_name='company',
        ),
    ]
