# Generated by Django 5.2.6 on 2025-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_city_company_leader_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidante',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leader',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
