# Generated by Django 5.2.6 on 2025-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_candidante_is_banned_leader_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidante',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='candidante',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания блокировки'),
        ),
        migrations.AddField(
            model_name='leader',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='leader',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания блокировки'),
        ),
    ]
