# Generated by Django 5.2.6 on 2025-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_candidante_ban_reason_candidante_ban_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidante',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='candidante',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
