# Generated by Django 5.2.6 on 2025-11-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidante',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
